# Generated by Django 6.0.1 on 2026-01-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0007_alter_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedFilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(unique=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
    ]
