# Generated by Django 6.0.1 on 2026-01-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0008_cachedfilepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='generator_key',
            field=models.CharField(choices=[('test', 'Test cards'), ('laundry', 'The Laundry Files RPG')], default='test'),
            preserve_default=False,
        ),
    ]
