# Generated by Django 6.0.1 on 2026-01-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0009_card_generator_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='generator_key',
            field=models.CharField(choices=[('_test', 'Test cards'), ('bfg', 'Battlefleet Gothic'), ('killteam', 'Kill-Team'), ('laundry', 'The Laundry Files RPG'), ('ten_metres', 'Ten Metres and Closing'), ('murder_mystery', 'The Curse of Pendleton Manor'), ('training_montage', 'Training Montage'), ('wraithsight', 'Wraithsight')]),
        ),
    ]
