# Generated by Django 6.0.1 on 2026-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0011_alter_card_generator_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfilepath',
            name='generator_key',
            field=models.CharField(choices=[('_test', 'Test cards'), ('bfg', 'Battlefleet Gothic'), ('killteam', 'Kill-Team'), ('laundry', 'The Laundry Files RPG'), ('little_pile_of_secrets', 'Little Pile of Secrets'), ('ten_metres', 'Ten Metres and Closing'), ('murder_mystery', 'The Curse of Pendleton Manor'), ('training_montage', 'Training Montage'), ('wraithsight', 'Wraithsight')], default='_test'),
            preserve_default=False,
        ),
    ]
