# Generated by Django 6.0.1 on 2026-01-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0012_cachedfilepath_generator_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
