# Generated by Django 6.0.1 on 2026-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0013_alter_card_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedfilepath',
            name='path',
            field=models.CharField(unique=True),
        ),
    ]
