# Generated by Django 6.0.1 on 2026-04-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painter', '0014_alter_cachedfilepath_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedfilepath',
            name='generator_key',
            field=models.CharField(choices=[('_test', 'Test cards'), ('bfg', 'Battlefleet Gothic'), ('goblin_quest', 'Goblin Quest'), ('killteam', 'Kill-Team'), ('laundry', 'The Laundry Files RPG'), ('little_pile_of_secrets', 'Little Pile of Secrets'), ('ten_metres', 'Ten Metres and Closing'), ('murder_mystery', 'The Curse of Pendleton Manor'), ('training_montage', 'Training Montage'), ('wraithsight', 'Wraithsight')]),
        ),
        migrations.AlterField(
            model_name='card',
            name='generator_key',
            field=models.CharField(choices=[('_test', 'Test cards'), ('bfg', 'Battlefleet Gothic'), ('goblin_quest', 'Goblin Quest'), ('killteam', 'Kill-Team'), ('laundry', 'The Laundry Files RPG'), ('little_pile_of_secrets', 'Little Pile of Secrets'), ('ten_metres', 'Ten Metres and Closing'), ('murder_mystery', 'The Curse of Pendleton Manor'), ('training_montage', 'Training Montage'), ('wraithsight', 'Wraithsight')]),
        ),
    ]
